const question = [
  {
    "question":
      "Identify the noun in the following sentence: 'The cat chased the mouse.'",
    "subject": "English",
    'topic': "Grammar",
    'difficulty': "Easy",
    'marks': 3,
  },
  {
    question: "What is the formula for calculating kinetic energy?",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the atomic number of carbon?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Name the process by which plants make their food.",
    subject: "Biology",
    topic: "Photosynthesis",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Solve for x: 2x + 5 = 15",
    subject: "Maths",
    topic: "Algebra",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "Who was the first president of the United States?",
    subject: "History",
    topic: "US Presidents",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the capital of Australia?",
    subject: "Geography",
    topic: "Countries and Capitals",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who wrote the play 'Romeo and Juliet'?",
    subject: "Literature",
    topic: "Shakespearean Plays",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the chemical formula for water?",
    subject: "Chemistry",
    topic: "Chemical Formulas",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the largest bone in the human body?",
    subject: "Biology",
    topic: "Anatomy",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "Solve: 3x - 7 = 14",
    subject: "Maths",
    topic: "Algebra",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What year did World War II end?",
    subject: "History",
    topic: "World Wars",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the currency of Brazil?",
    subject: "Geography",
    topic: "Countries and Currencies",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question:
      "What is the process of converting sunlight into electricity called?",
    subject: "Physics",
    topic: "Solar Energy",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "What is a simile?",
    subject: "English",
    topic: "Language Techniques",
    difficulty: "Easy",
    marks: 3,
  },

  {
    question: "Name the author of the book 'To Kill a Mockingbird'.",
    subject: "Literature",
    topic: "Modern Classics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the chemical symbol for sodium?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the function of the mitochondria in a cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Simplify: 4(3x + 2) - 2x",
    subject: "Maths",
    topic: "Algebra",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "What is the main function of the heart?",
    subject: "Biology",
    topic: "Human Anatomy",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who discovered penicillin?",
    subject: "Chemistry",
    topic: "Medicinal Chemistry",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "What is the Pythagorean theorem?",
    subject: "Maths",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Which treaty ended World War I?",
    subject: "History",
    topic: "World War I",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question:
      "What is the literary device used to compare two unlike things using 'like' or 'as'?",
    subject: "English",
    topic: "Literary Devices",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Name the largest ocean in the world.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the law of conservation of energy?",
    subject: "Physics",
    topic: "Energy Conservation",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question:
      "What is the structure responsible for storing genetic information in a cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the capital of India?",
    subject: "Geography",
    topic: "Countries and Capitals",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Who is known as the 'Father of the Nation' in India?",
    subject: "History",
    topic: "Indian Freedom Struggle",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which river is known as the Ganges in India?",
    subject: "Geography",
    topic: "Rivers",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Name the national emblem of India.",
    subject: "General Knowledge",
    topic: "Indian Symbols",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "When is India's Independence Day celebrated?",
    subject: "History",
    topic: "Indian Independence",
    difficulty: "Hard",
    marks: 7,
  },
  {
    question: "Who composed the Indian National Anthem, 'Jana Gana Mana'?",
    subject: "Music",
    topic: "National Anthem",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question: "Name the highest mountain peak in India.",
    subject: "Geography",
    topic: "Mountains",
    difficulty: "Medium",
    marks: 6,
  },
  {
    question: "Which city is known as the 'Pink City' of India?",
    subject: "Geography",
    topic: "Indian Cities",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Who was the first female Prime Minister of India?",
    subject: "History",
    topic: "Indian Prime Ministers",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question: "Name the national animal of India.",
    subject: "General Knowledge",
    topic: "Indian Symbols",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the atomic number of carbon?",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the chemical symbol for carbon?",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Name the two allotropes of carbon known as 'jewel' and 'black'",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which form of carbon is used in pencils?",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question:
      "What is the process called when carbon dioxide is converted into organic compounds by plants using sunlight?",
    subject: "Biology",
    topic: "Photosynthesis",
    difficulty: "Medium",
    marks: 6,
  },
  {
    question:
      "Name a polymer of carbon that is widely used in plastic bottles.",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Which gas is produced when carbon reacts with hydrochloric acid?",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the primary source of carbon in the Earth's atmosphere?",
    subject: "Geology",
    topic: "Carbon Cycle",
    difficulty: "Hard",
    marks: 7,
  },
  {
    question: "Name the hardest known natural form of carbon.",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "What is the term for the process of removing carbon dioxide from the atmosphere and storing it?",
    subject: "Environmental Science",
    topic: "Carbon Capture",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "What is the formula to calculate force?",
    subject: "Physics",
    topic: "Force",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Define Newton's Second Law of Motion.",
    subject: "Physics",
    topic: "Laws of Motion",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the SI unit of energy?",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Explain the concept of acceleration.",
    subject: "Physics",
    topic: "Motion",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the law of conservation of energy?",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the electromagnetic wave with the shortest wavelength.",
    subject: "Physics",
    topic: "Electromagnetic Spectrum",
    difficulty: "Medium",
    marks: 6,
  },
  {
    question: "What is the formula to calculate work done?",
    subject: "Physics",
    topic: "Work and Energy",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question: "Define Ohm's Law.",
    subject: "Physics",
    topic: "Electricity",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the SI unit of electric charge?",
    subject: "Physics",
    topic: "Electricity",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Explain the concept of momentum.",
    subject: "Physics",
    topic: "Momentum",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "What is the formula for calculating the gravitational force between two objects?",
    subject: "Physics",
    topic: "Gravitation",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Explain the concept of refraction.",
    subject: "Physics",
    topic: "Optics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the difference between scalar and vector quantities?",
    subject: "Physics",
    topic: "Scalars and Vectors",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Define the term 'terminal velocity'.",
    subject: "Physics",
    topic: "Motion",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the law of reflection?",
    subject: "Physics",
    topic: "Optics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Explain the concept of nuclear fission.",
    subject: "Physics",
    topic: "Nuclear Physics",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the SI unit of power?",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Define the term 'moment of inertia'.",
    subject: "Physics",
    topic: "Rotational Motion",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Explain the phenomenon of electromagnetic induction.",
    subject: "Physics",
    topic: "Electromagnetism",
    difficulty: "Medium",
    marks: 6,
  },
  {
    question: "What is the formula to calculate kinetic energy?",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question:
      "What is the formula for calculating the perimeter of a rectangle?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Define what a polygon is.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question:
      "Calculate the area of a triangle with base 6 units and height 8 units.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the formula for finding the volume of a sphere?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 6,
  },
  {
    question: "Define what similar triangles are.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the formula to calculate the surface area of a cube?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 5,
  },

  {
    question:
      "Identify the noun in the following sentence: 'The cat chased the mouse.'",
    subject: "English",
    topic: "Grammar",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the formula for calculating kinetic energy?",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the atomic number of carbon?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Name the process by which plants make their food.",
    subject: "Biology",
    topic: "Photosynthesis",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Solve for x: 2x + 5 = 15",
    subject: "Maths",
    topic: "Algebra",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "Who was the first president of the United States?",
    subject: "History",
    topic: "US Presidents",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the capital of Australia?",
    subject: "Geography",
    topic: "Countries and Capitals",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who wrote the play 'Romeo and Juliet'?",
    subject: "Literature",
    topic: "Shakespearean Plays",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the chemical formula for water?",
    subject: "Chemistry",
    topic: "Chemical Formulas",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the largest bone in the human body?",
    subject: "Biology",
    topic: "Anatomy",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "Solve: 3x - 7 = 14",
    subject: "Maths",
    topic: "Algebra",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What year did World War II end?",
    subject: "History",
    topic: "World Wars",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the currency of Brazil?",
    subject: "Geography",
    topic: "Countries and Currencies",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question:
      "What is the process of converting sunlight into electricity called?",
    subject: "Physics",
    topic: "Solar Energy",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "What is a simile?",
    subject: "English",
    topic: "Language Techniques",
    difficulty: "Easy",
    marks: 3,
  },

  {
    question: "Name the author of the book 'To Kill a Mockingbird'.",
    subject: "Literature",
    topic: "Modern Classics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the chemical symbol for sodium?",
    subject: "Chemistry",
    topic: "Elements",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the function of the mitochondria in a cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Simplify: 4(3x + 2) - 2x",
    subject: "Maths",
    topic: "Algebra",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "What is the main function of the heart?",
    subject: "Biology",
    topic: "Human Anatomy",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Who discovered penicillin?",
    subject: "Chemistry",
    topic: "Medicinal Chemistry",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "What is the Pythagorean theorem?",
    subject: "Maths",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Which treaty ended World War I?",
    subject: "History",
    topic: "World War I",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question:
      "What is the literary device used to compare two unlike things using 'like' or 'as'?",
    subject: "English",
    topic: "Literary Devices",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Name the largest ocean in the world.",
    subject: "Geography",
    topic: "Oceans",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the law of conservation of energy?",
    subject: "Physics",
    topic: "Energy Conservation",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question:
      "What is the structure responsible for storing genetic information in a cell?",
    subject: "Biology",
    topic: "Cell Biology",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the capital of India?",
    subject: "Geography",
    topic: "Countries and Capitals",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Who is known as the 'Father of the Nation' in India?",
    subject: "History",
    topic: "Indian Freedom Struggle",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which river is known as the Ganges in India?",
    subject: "Geography",
    topic: "Rivers",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Name the national emblem of India.",
    subject: "General Knowledge",
    topic: "Indian Symbols",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "When is India's Independence Day celebrated?",
    subject: "History",
    topic: "Indian Independence",
    difficulty: "Hard",
    marks: 7,
  },
  {
    question: "Who composed the Indian National Anthem, 'Jana Gana Mana'?",
    subject: "Music",
    topic: "National Anthem",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question: "Name the highest mountain peak in India.",
    subject: "Geography",
    topic: "Mountains",
    difficulty: "Medium",
    marks: 6,
  },
  {
    question: "Which city is known as the 'Pink City' of India?",
    subject: "Geography",
    topic: "Indian Cities",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Who was the first female Prime Minister of India?",
    subject: "History",
    topic: "Indian Prime Ministers",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question: "Name the national animal of India.",
    subject: "General Knowledge",
    topic: "Indian Symbols",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the atomic number of carbon?",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the chemical symbol for carbon?",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Name the two allotropes of carbon known as 'jewel' and 'black'",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Which form of carbon is used in pencils?",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question:
      "What is the process called when carbon dioxide is converted into organic compounds by plants using sunlight?",
    subject: "Biology",
    topic: "Photosynthesis",
    difficulty: "Medium",
    marks: 6,
  },
  {
    question:
      "Name a polymer of carbon that is widely used in plastic bottles.",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "Which gas is produced when carbon reacts with hydrochloric acid?",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the primary source of carbon in the Earth's atmosphere?",
    subject: "Geology",
    topic: "Carbon Cycle",
    difficulty: "Hard",
    marks: 7,
  },
  {
    question: "Name the hardest known natural form of carbon.",
    subject: "Chemistry",
    topic: "Carbon",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "What is the term for the process of removing carbon dioxide from the atmosphere and storing it?",
    subject: "Environmental Science",
    topic: "Carbon Capture",
    difficulty: "Hard",
    marks: 6,
  },
  {
    question: "What is the formula to calculate force?",
    subject: "Physics",
    topic: "Force",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Define Newton's Second Law of Motion.",
    subject: "Physics",
    topic: "Laws of Motion",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the SI unit of energy?",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Explain the concept of acceleration.",
    subject: "Physics",
    topic: "Motion",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the law of conservation of energy?",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Name the electromagnetic wave with the shortest wavelength.",
    subject: "Physics",
    topic: "Electromagnetic Spectrum",
    difficulty: "Medium",
    marks: 6,
  },
  {
    question: "What is the formula to calculate work done?",
    subject: "Physics",
    topic: "Work and Energy",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question: "Define Ohm's Law.",
    subject: "Physics",
    topic: "Electricity",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the SI unit of electric charge?",
    subject: "Physics",
    topic: "Electricity",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Explain the concept of momentum.",
    subject: "Physics",
    topic: "Momentum",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question:
      "What is the formula for calculating the gravitational force between two objects?",
    subject: "Physics",
    topic: "Gravitation",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Explain the concept of refraction.",
    subject: "Physics",
    topic: "Optics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "What is the difference between scalar and vector quantities?",
    subject: "Physics",
    topic: "Scalars and Vectors",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Define the term 'terminal velocity'.",
    subject: "Physics",
    topic: "Motion",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "What is the law of reflection?",
    subject: "Physics",
    topic: "Optics",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question: "Explain the concept of nuclear fission.",
    subject: "Physics",
    topic: "Nuclear Physics",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the SI unit of power?",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Define the term 'moment of inertia'.",
    subject: "Physics",
    topic: "Rotational Motion",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "Explain the phenomenon of electromagnetic induction.",
    subject: "Physics",
    topic: "Electromagnetism",
    difficulty: "Medium",
    marks: 6,
  },
  {
    question: "What is the formula to calculate kinetic energy?",
    subject: "Physics",
    topic: "Energy",
    difficulty: "Easy",
    marks: 4,
  },
  {
    question:
      "What is the formula for calculating the perimeter of a rectangle?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Easy",
    marks: 3,
  },
  {
    question: "Define what a polygon is.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 4,
  },
  {
    question:
      "Calculate the area of a triangle with base 6 units and height 8 units.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the formula for finding the volume of a sphere?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 6,
  },
  {
    question: "Define what similar triangles are.",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 5,
  },
  {
    question: "What is the formula to calculate the surface area of a cube?",
    subject: "Mathematics",
    topic: "Geometry",
    difficulty: "Medium",
    marks: 5,
  },
]


module.exports = question